CTAFramework/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, \
    PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path
from django.views.generic.base import TemplateView

from apps.Users.views import RequestAccessView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Products.urls')),
    url(r'^apis/', include('apps.apis.urls')),
    #url(r'^apis/docs/', include('rest_framework_docs.urls')),
    url(r'^servers/', include('apps.Servers.urls')),
    url(r'^testings/', include('apps.Testings.urls')),
    url(r'^users/', include('apps.Users.urls')),
    url(r'^request-access/', RequestAccessView.as_view(), name='request-access'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name="reset-password"),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('help/', TemplateView.as_view(template_name='index.html'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/Testings/urls.py
from django.conf.urls import url

from .views import KeyWordsView, NewKeywordView, EditKeywordView, DeleteKeywordView, \
    CollectionsView, NewCollectionsView, EditCollectionsView, DeleteCollectionsView, \
    TestCaseView, NewTestCaseView, EditTestCaseView, DeleteTestCaseView, \
    TestSuiteView, NewTestSuiteView, EditTestSuiteView, DeleteTestSuiteView, \
    DownloadKeywordView, DownloadTestSuiteView, DownloadTestcaseView, DeleteImportedScriptView, \
    NewImportedView, EditImportedView, ImportedView, RunScriptView

urlpatterns = [
    url(r'^keywords/$', KeyWordsView.as_view(), name="keywords"),
    url(r'^keywords/new/$', NewKeywordView.as_view(), name="new-keywords"),
    url(r'^keywords/edit/(?P<pk>\d+)$', EditKeywordView.as_view(), name="edit-keywords"),
    url(r'^keywords/(?P<pk>\d+)/delete/$', DeleteKeywordView.as_view(), name="delete-keywords"),
    url(r'^keywords/download/(?P<pk>\d+)$',DownloadKeywordView.as_view(),name="download-keywords"),
    # TestCase
    url(r'^testcases/$', TestCaseView.as_view(), name="testcases"),
    url(r'^testcases/new/$', NewTestCaseView.as_view(), name="new-testcase"),
    url(r'^testcases/edit/(?P<pk>\d+)$', EditTestCaseView.as_view(), name="edit-testcase"),
    url(r'^testcases/(?P<pk>\d+)/delete/$', DeleteTestCaseView.as_view(), name="delete-keywords"),
    url(r'^testcases/(?P<pk>\d+)/download/$', DownloadTestcaseView.as_view(), name="download-testcase"),
    # TestSuites
    url(r'^testsuites/$', TestSuiteView.as_view(), name="testsuites"),
    url(r'^testsuites/new/$', NewTestSuiteView.as_view(), name="new-testsuites"),
    url(r'^testsuites/edit/(?P<pk>\d+)$', EditTestSuiteView.as_view(), name="edit-testsuites"),
    url(r'^testsuites/(?P<pk>\d+)/delete/$', DeleteTestSuiteView.as_view(), name="delete-testsuite"),
    url(r'^testsuites/(?P<pk>\d+)/download/$', DownloadTestSuiteView.as_view(), name="download-testsuite"),
    # Collections
    url(r'^collections/$', CollectionsView.as_view(), name="collections"),
    url(r'^collections/new/$', NewCollectionsView.as_view(), name="new-collections"),
    url(r'^collections/(?P<pk>\d+)/$', EditCollectionsView.as_view(), name='edit-collections'),
    url(r'^collections/(?P<pk>\d+)/delete/$', DeleteCollectionsView.as_view(), name="delete-collections"),
    # Import
    url(r'^imported/$', ImportedView.as_view(), name="imported-scripts"),
    url(r'^import/$', NewImportedView.as_view(), name="new-import-script"),
    url(r'^import/(?P<type_script>[\w-]+)/(?P<pk>\d+)/edit/$', EditImportedView.as_view(), name="edit-import-script"),
    url(r'^import/(?P<type_script>[\w-]+)/(?P<pk>\d+)/delete/$', DeleteImportedScriptView.as_view(), name="delete-import-script"),
    # Run scripts
    url(r'^(?P<pk>\d+)/(?P<type_script>\d+)/run$', RunScriptView.as_view(), name="run-script"),
    # Stepper
    url(r'^collections/(?P<stepper>[-\w]+)/new/$', NewCollectionsView.as_view(), name="new-collections-stepper"),
    url(r'^collections/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditCollectionsView.as_view(), name='edit-collections'),
    url(r'^keywords/(?P<stepper>[-\w]+)/new/$', NewKeywordView.as_view(), name="new-keywords-stepper"),
    url(r'^keywords/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditKeywordView.as_view(), name="edit-keywords-stepper"),
    url(r'^testcases/(?P<stepper>[-\w]+)/new/$', NewTestCaseView.as_view(), name="new-testcase-stepper"),
    url(r'^testcases/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditTestCaseView.as_view(), name='edit-testcase-stepper'),
    url(r'^testsuites/(?P<stepper>[-\w]+)/new/$', NewTestSuiteView.as_view(), name="new-testsuites-stepper"),
    url(r'^testsuites/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditTestSuiteView.as_view(), name="edit-testsuites-stepper"),
    url(r'^(?P<pk>\d+)/(?P<type_script>\d+)/(?P<stepper>[-\w]+)/run$', RunScriptView.as_view(), name="run-script-stepper"),
]

apps/Testings/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from apps.Users.models import User
from apps.Products.models import Source
from apps.Servers.models import ServerProfile

SCRIPT_TYPE_CHOICES = (
    (1, _("Native")),
    (2, _("Imported")),
)


class Collection(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    description = models.TextField(_('description'), blank=True, null=True)
    product = models.ForeignKey(Source, related_name="products", on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "collections"
        verbose_name = _('collection')
        verbose_name_plural = _('collections')
        ordering = ['name']

    def __str__(self):
        return '{0}'.format(self.name)


class Keyword(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    description = models.TextField(_('description'), blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    script = models.TextField(_('script'))
    values = models.TextField(_('values'), blank=True)
    extra_imports = models.TextField(_('extra imports '), blank=True)
    created_at = models.DateTimeField(_('created_at'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    collection = models.ManyToManyField(Collection, blank=True)
    script_type = models.PositiveIntegerField(_('script type'), choices=SCRIPT_TYPE_CHOICES, default=1)

    class Meta:
        db_table = "keywords"
        verbose_name = _('keyword')
        verbose_name_plural = _('keywords')

    def __str__(self):
        return '{0}'.format(self.name)


class Phase(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    product = models.ForeignKey(Source, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "phases"
        verbose_name = _('phase')
        verbose_name_plural = _('phases')

    def __str__(self):
        return '{0}'.format(self.name)


class TestCase(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    description = models.TextField(_('description'), blank=True, null=True)
    script = models.TextField(_('script'), blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    collection = models.ManyToManyField(Collection)
    functions = models.CharField(_('functions'), blank=True, max_length=100)
    phase = models.ForeignKey(Phase, on_delete=models.DO_NOTHING)
    values = models.TextField(_('values'), blank=True)
    extra_imports = models.TextField(_('extra imports '), blank=True)
    created_at = models.DateTimeField(_('created_at'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    script_type = models.PositiveIntegerField(_('script type'), choices=SCRIPT_TYPE_CHOICES, default=1)

    class Meta:
        verbose_name = _('test case')
        verbose_name_plural = _('test cases')
        db_table = 'testcases'

    def __str__(self):
        return '{0}'.format(self.name)


class TestSuite(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    description = models.TextField(_('description'), blank=True, null=True)
    script = models.TextField(_('script'), blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    collection = models.ManyToManyField(Collection)
    values = models.TextField(_('values'), blank=True)
    extra_imports = models.TextField(_('extra imports '), blank=True)
    created_at = models.DateTimeField(_('created_at'), auto_now_add=True, editable=False)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    script_type = models.PositiveIntegerField(_('script type'), choices=SCRIPT_TYPE_CHOICES, default=1)

    class Meta:
        verbose_name = _('test suite')
        verbose_name_plural = _('test suites')
        db_table = 'testsuites'

    def __str__(self):
        return '{0}'.format(self.name)

apps/Testings/forms.py
from django import forms

from .models import Collection, Keyword, Phase, Collection
from apps.Products.models import Source

SCRIPT_TYPE_CHOICES = (
    (None, 'Choose a script type'),
    ('keyword', 'Keyword'),
    ('testcase', 'Test case'),
    ('testsuite', 'Test suite'),
)


class CollectionForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = [
            'name',
            'description',
            'product',
        ]
        widgets = {
            'product': forms.Select(attrs={'required': True}),
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'})
        }

    def __init__(self, *args, **kwargs):
        """This filter only for sources in the category 3(products)"""
        super(CollectionForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Source.objects.filter(category=3)


class NewImportScriptForm(forms.Form):
    script_type = forms.CharField(widget=forms.Select(choices=SCRIPT_TYPE_CHOICES))
    collection = forms.ModelChoiceField(queryset=Collection.objects.all())
    phase = forms.ModelChoiceField(queryset=Phase.objects.all())
    name = forms.CharField(max_length=100)
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
    file_script = forms.FileField()


class EditImportScriptForm(forms.ModelForm):
    class Meta:
        model = Keyword
        fields = [
            'name',
            'description',
            'script'
        ]
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'}),
            'script': forms.Textarea(attrs={
                'class': 'materialize-textarea',
                'spellcheck': 'false',
                'style': 'max-height: 25vh; overflow: scroll'
            })
        }

apps/Testings/templates/collections.html
{% extends "base.html" %}
{% block title %}Collections{% endblock %}{% block subtitle %}Collections{% endblock %}
{% load permission_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">
                <p>
                    A collection is a group of Keywords/Test cases/Test Suites for a specific purpose.
                </p>
            </div>
        </div>
        <table class="datatable">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Edit</th>
            </tr>
            </thead>
        </table>
        {% if user|can:'create_collection' %}
            <div class="fixed-action-btn">
                <a href="{% url "new-collections" %}"
                   class="btn-floating btn-large waves-effect waves-light blue-grey" style="float:left;margin:0.7rem;right:260px;bottom:5px;">
                   <i class="material-icons">add</i></a>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% load static %}
{% block extraStyles %}
    <link rel="stylesheet" href="{% static "css/dataTablesMaterial.css" %}">
{% endblock %}
{% block extraScripts %}
    <script src="{% static "js/datatables.min.js" %}"></script>
    <script src="{% static "js/DTBoilerPlate.js" %}"></script>
    <script>
        $(document).ready(function () {
            var config = [{
                "targets": 2,
                data: function (row) {
                    return "<div>" +
                        {% if user|can:'update_collection' %}
                            "<a class='btn' href='/testings/collections/" + row[2]
                            + "'><i class='material-icons'>edit</i></a>" +
                            "   " +
                        {% endif %}
                        {% if user|can:'delete_collection' %}
                            "<a class='btn red' href='/testings/collections/" + row[2]
                            + "/delete/'><i class='material-icons'>delete</i></a>" +
                        {% endif %}
                        "</div>";
                }
            }];
            dtStart("{% url "api-collections" %}", config)
        });
    </script>
{% endblock %}

apps/Testings/templates/control-flow-block.html
<div class="center"><b class="pink-text">Select Elements to Drag</b><i style="float: right;" class="tiny material-icons tooltipped" data-position="bottom" data-tooltip="Select the command and drag it to the Drag and Drop window">help_outline</i></div>
<div class="card">
    <div class="card-content">
        <label for="cfs">
            Control Flow Sentences
        </label>
        <div id="flowSentenceContainer"></div>
    </div>
</div>
<script>
    /* Search for Control Flow Sentences Commands */
    getFlowSentenceCommands({
        "data": {"category": 1, "page_size": 10, "extra": 0},
        "id_div_accordion": "controlFlowCommandsPanel"
    });

    function getFlowSentenceCommands(config) {
        $.ajax({
            url: "{% url 'api-commands' %}",
            type: 'GET',
            data: config.data,
            success: function (data) {
                if (data.results) {
                    populateCommandsPanel(data.results);
                }
            },
            error: function (error) {
                drawMessage(error.responseJSON.text, 'red');
                console.log("Error retrieving commands when website is loaded " + error);
                return false;
            }
        });
    }

    function populateCommandsPanel(commands) {
        commands.forEach(function (commandJSON) {
            var draggableNode = document.createElement("div");

            draggableNode.className = "drag-drop-item center";
            draggableNode.id = commandJSON.id + "-drag-drop";
            draggableNode.draggable = true;
            draggableNode.setAttribute("ondragstart", "drag(event)");
            draggableNode.innerHTML = commandJSON.name;
            var commandsPanelControlFlow = document.getElementById('flowSentenceContainer');
            commandsPanelControlFlow.appendChild(draggableNode);
        });
    }
</script>

apps/Testings/templates/delete-imported-script.html
{% extends "base.html" %}
{% block title %}Delete  {{ object.name }}{% endblock %}
{% block subtitle %}Delete  {{ object.name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="card-title">Are you sure you want to delete the following Script?</p>
                        <ul>
                            <li><b>Name:</b> {{ object.name }}</li>
                            <li><b>Description:</b> {{ object.description }}</li>
                        </ul>
                        <div class="center">
                            <input type="submit" value="Confirm" class="btn red"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn left-button ">
        <a href="{% url "imported-scripts" %}" id="btn_play"
           class="btn-floating btn-large waves-effect waves-light grey">
            <i class="material-icons">arrow_back</i></a>
    </div>
{% endblock %}

apps/Testings/templates/delete-keyword.html
{% extends "base.html" %}
{% block title %}Delete  {{ object.name }}{% endblock %}
{% block subtitle %}Delete  {{ object.name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="card-title">Are you sure you want to delete the following Keyword?</p>
                        <ul>
                            <li><b>Name:</b> {{ object.name }}</li>
                            <li><b>Description:</b> {{ object.description }}</li>
                        </ul>
                        <div class="center">
                            <input type="submit" value="Confirm" class="btn red"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

       <div class="fixed-action-btn left-button ">
        <a href="{% url "keywords" %}" id="btn_play"
           class="btn-floating btn-large waves-effect waves-light grey">
            <i class="material-icons">arrow_back</i></a>
    </div>
{% endblock %}

apps/Testings/templates/download-testsuite.html
{% extends "base.html" %}
{% block title %}Download  {{ data.Name }}{% endblock %}
{% block subtitle %}Download  {{ data.Name }}{% endblock %}
{% block content %}
<script src="/static/js/jszip.js" type ="text/javascript"></script>
<script src="/static/js/FileSaver.js" type ="text/javascript"></script>
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action='' method="POST">
                        {% csrf_token %}
                        <p class="card-title">You are about to download the following Test Suite: </p>
                        <ul>
                            <li><b>Name:</b> {{ data.Name }}</li>
                            <li><b>Description:</b> {{ data.Description }}</li>
                        </ul>
                        <p style="text-align: justify;">
                            Click the left button to download just the testsuite content, or click the right one in order to download it with all dependencies 
                        </p>
                        <div class="left">
                            <button class="btn blue" onclick="save()">RAW</button>
                        </div>

                        <div class="right">
                            <button class="btn green" onclick="savezipfile()" >FULL</button>
                        </div>
 
                    </form>
                    <script type ="text/javascript">
                        
                        var data1="{{data.Name}}"
                        var data2=`{{data.Script}}`
                        function save() {
                        var blob = new Blob([data2], {type: 'text/plain'});
                        if(window.navigator.msSaveOrOpenBlob) {
                            window.navigator.msSaveBlob(blob, data1);
                        }
                        else{
                            var elem = window.document.createElement('a');
                            elem.href = window.URL.createObjectURL(blob);
                            elem.download = data1+".robot";        
                            document.body.appendChild(elem);
                            elem.click();        
                            document.body.removeChild(elem);
                        }
                    }
                    </script>
                    
                    <script>
                        var data1="{{data.Name}}"
                        var data2=`{{data.Script}}`
                        
                        function savezipfile() {
                        var blob = new Blob([data2], {type: 'text/plain'});
                        if(window.navigator.msSaveOrOpenBlob) {
                            window.navigator.msSaveBlob(blob, data1);
                        }
                        else{
                            var zip = new JSZip();

                            zip.file(data1 + '.robot', data2);
                            
                            {% for mykey, myvalue in data.Dependencies.items %}
                                var data3 = "{{ mykey }}"
                                var data4 = `{{ myvalue }}`
                                zip.file(data3 + '.robot', data4);
                            {% endfor %}

                            zip.generateAsync({type:"blob"}).then(function(content) {
                                // see FileSaver.js
                                saveAs(content, data1 + ".zip");
                            });
                        }
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn left-button ">
        <a href="{% url "testsuites" %}" id="btn_play"
           class="btn-floating btn-large waves-effect waves-light grey">
            <i class="material-icons">arrow_back</i></a>
    </div>
{% endblock %}

apps/Testings/templates/properties-block.html
<div id="propertiesPanelContainer" class="card">

    <div id="propertiesPannel" class="card-content propertiesPannel">
        <p id="currentEditing">Editing ID</p>
        <form action="">

            <div id="defaultEditing" class="input-field">
                <input type="text" name="value">
                <label for="value">Value</label>
            </div>
            <div class="center">
                <input type="submit" class="btn" value="Create"
                       onclick="saveParametersFromInput();">
            </div>
        </form>
    </div>
</div>

apps/Testings/templates/run_script.html
{% extends "base.html" %}
{% block title %}Run Script{% endblock %}{% block subtitle %}Run Script{% endblock %}
{% block content %}
    <div class="row">
        {% csrf_token %}
        <input type="hidden" id="object" value="{{ obj.id }}">
        <input type="hidden" id="object_type" value="{{ type_id }}">
        <div class="col l1 ">
        </div>
        <div class="col s12 l5">
            <div class="section">
                <h5 class="blue-grey-text">{{ type }} - {{ obj.name }}</h5>
                <ul>
                    {% if obj.description %}
                        <li><b>Description:</b> <i>{{ obj.description }}</i></li>
                    {% endif %}
                    <li><b>Created by: </b><i>
                        {% if obj.user.first_name %}
                            {{ obj.user.first_name }} {{ obj.user.last_name }}
                        {% else %}
                            {{ obj.user.email }}
                        {% endif %}
                    </i></li>
                    <li><b>Created:</b> <i>{{ obj.created_at }}</i></li>
                    <li><b>Last Update:</b> <i>{{ obj.modified }}</i></li>
                    {% if type_id is 1 %}
                        <li><b>Origin: </b><i>{{ obj.get_script_type_display }}</i></li>
                    {% endif %}
                    {% if type_id is 2 %}
                        <li><b>Phase: </b><i>{{ obj.phase }}</i></li>
                    {% endif %}
                    <li><b>Collection:</b>
                        <ul>
                            {% for col in obj.collection.all %}
                                <li>-<b>Name: </b><i>{{ col }}</i></li>
                                {% if col.description %}
                                    <li>-<b>Description: </b><i>{{ col.description }}</i></li>
                                {% endif %}
                                <li>-<b>Product: </b><i>{{ col.product }}</i></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <ul class="collapsible" data-collapsible="accordion">
                    <li>
                        <div class="collapsible-header"><i class="material-icons blue-text">remove_red_eye</i>Preview
                            Script
                        </div>
                        <div class="collapsible-body">
                            {{ script | safe }}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col l1 ">
        </div>
        <div class="col s12 l4">
            <div class="section">
                <div class="input-field col s12">
                    <select id="connection" onchange="enable_run()">
                        <option value="" disabled selected>Choose your option</option>

                    </select>
                    <label>Connection Profile</label>
                </div>

                <div class="input-field col s12">
                    <select id="variables" multiple>
                        <option value="" disabled selected>Choose your option</option>
                    </select>
                    <label>Variables Profile</label>
                </div>
                <div class="center">
                    <button id="btn_run" type="button" class="btn waves-effect waves-light" onclick="runScript()" disabled>Run</button>
                </div>
            </div>
        </div>
    </div>

    {#    - - - -  Back button conditions - - - - - #}
    {% if stepper != 'stepper' %}
    <div class="fixed-action-btn left-button ">
        {% if type_id is 1 and obj.script_type is 1 %}
            <a href="{% url "keywords" %}" id="btn_play"
               class="btn-floating btn-large waves-effect waves-light grey">
                <i class="material-icons">arrow_back</i></a>
        {% elif type_id is 1 and obj.script_type is 2 %}
            <a href="{% url "imported-scripts" %}" id="btn_play"
               class="btn-floating btn-large waves-effect waves-light grey">
                <i class="material-icons">arrow_back</i></a>
        {% elif type_id is 2 %}
            <a href="{% url "testcases" %}" id="btn_play"
               class="btn-floating btn-large waves-effect waves-light grey">
                <i class="material-icons">arrow_back</i></a>
        {% elif type_id is 3 %}
            <a href="{% url "testsuites" %}" id="btn_play"
               class="btn-floating btn-large waves-effect waves-light grey">
                <i class="material-icons">arrow_back</i></a>
        {% endif %}
    </div>
    {% endif %}
{% endblock %}
{% load static %}
{% load compress %}
{% block extraStyles %}
    {% compress css %}
        <link rel="stylesheet" href="{% static "css/highlight.css" %}">
    {% endcompress %}
{% endblock %}

{% block extraScripts %}
    {% compress js %}
        <script type="text/javascript">
            var _object_pk = document.getElementById('object').value;
            var _object_type = document.getElementById('object_type').value;

            var _selectConnection = document.getElementById('connection');
            var _selectVariables = document.getElementById('variables');

            /*Global variables*/
            get_profiles(1, _selectVariables);
            /*Local connection */
            get_profiles(2, _selectConnection);
            /*Jenkins connection */
            get_profiles(3, _selectConnection);

            function get_profiles(_category, _element) {
                $.ajax({
                    url: "{% url "api-profiles" %}",
                    type: "GET",
                    data: {
                        category: _category
                    },
                    success: function (data) {
                        data.forEach(function (v, k) {
                            var _option = document.createElement("option");
                            _option.text = v.name;
                            _option.value = v.id;
                            _element.appendChild(_option);
                        });
                        $('select').material_select();
                    }, error: function (err) {
                        console.log(err)
                    }
                })
            }

            function setProfiles() {
                var _profiles = [];
                if ($('#variables').val()) {
                    $('#variables').val().forEach(function (v, k) {
                        _profiles.push(v)
                    });
                }
                _profiles.push(_selectConnection.value);
                return JSON.stringify(_profiles)
            }

            function runScript() {
                $.ajax({
                    url: "{% url "run-on-server" %}",
                    type: "POST",
                    data: {
                        id: _object_pk,
                        profile: setProfiles,
                        type_script: _object_type
                    },
                    success: function (data) {
                        drawMessage("Script send to Queue", 'green');
                        var $toastContent = $('<span>Click on "GO" button to go Task list </span>').add($(
                            '<a href="/home/" class="btn-flat white-text toast-action">Go</a>'));
                        Materialize.toast($toastContent, 12000, 'blue');
                    }, error: function (err) {
                        drawMessage(err.responseJSON.text, 'red');
                    }
                });
            }

            function enable_run(){
                var _btn_run = document.getElementById('btn_run');
                _btn_run.disabled = false;
            }
        </script>
    {% endcompress %}
{% endblock %}