CTAFramework/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, \
    PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path
from django.views.generic.base import TemplateView

from apps.Users.views import RequestAccessView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Products.urls')),
    url(r'^apis/', include('apps.apis.urls')),
    #url(r'^apis/docs/', include('rest_framework_docs.urls')),
    url(r'^servers/', include('apps.Servers.urls')),
    url(r'^testings/', include('apps.Testings.urls')),
    url(r'^users/', include('apps.Users.urls')),
    url(r'^request-access/', RequestAccessView.as_view(), name='request-access'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name="reset-password"),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('help/', TemplateView.as_view(template_name='index.html'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/Servers/urls.py
from django.conf.urls import url
from .views import ServerTemplateView, NewServerTemplate, EditServerTemplate, DeleteServerTemplate, ServerProfileView, \
    NewServerProfileView, EditServerProfileView, \
    DeleteServerProfile, ParametersView, NewParametersView, EditParametersView, DeleteParametersView

urlpatterns = [
    # Templates CRUD
    url(r'^templates/$', ServerTemplateView.as_view(), name='servers-templates'),
    url(r'^templates/new/$', NewServerTemplate.as_view(), name='new-server-template'),
    url(r'^templates/(?P<pk>\d+)/$', EditServerTemplate.as_view(), name='edit-server-template'),
    url(r'^templates/(?P<pk>\d+)/delete/$', DeleteServerTemplate.as_view(), name='delete-server-template'),
    # Profiles CRUD
    url(r'^profiles/$', ServerProfileView.as_view(), name='servers-profiles'),
    url(r'^profiles/new/$', NewServerProfileView.as_view(), name='new-server-profile'),
    url(r'^profiles/(?P<pk>\d+)/$', EditServerProfileView.as_view(), name='edit-server-profile'),
    url(r'^profiles/(?P<pk>\d+)/delete/$', DeleteServerProfile.as_view(), name='delete-server-profile'),
    # Parameters CRUD
    url(r'^parameters/$', ParametersView.as_view(), name='parameters'),
    url(r'^parameters/new$', NewParametersView.as_view(), name='new-parameters'),
    url(r'^parameters/(?P<pk>\d+)/$', EditParametersView.as_view(), name='edit-parameters'),
    url(r'^parameters/(?P<pk>\d+)/delete/$', DeleteParametersView.as_view(), name='delete-parameters'),
    # Stepper
    url(r'^templates/(?P<stepper>[-\w]+)/new/$', NewServerTemplate.as_view(), name='new-server-template-stepper'),
    url(r'^templates/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditServerTemplate.as_view(), name='edit-server-template-stepper'),
    url(r'^profiles/(?P<stepper>[-\w]+)/new/$', NewServerProfileView.as_view(), name='new-server-profile-stepper'),
    url(r'^profiles/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditServerProfileView.as_view(), name='edit-server-profile-stepper'),
    url(r'^parameters/(?P<stepper>[-\w]+)/new$', NewParametersView.as_view(), name='new-parameters-stepper'),
    url(r'^parameters/(?P<pk>\d+)/(?P<stepper>[-\w]+)/edit/$', EditParametersView.as_view(), name='edit-parameters-stepper'),
]

apps/Servers/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from apps.Users.models import User

VARIABLES = 1
LOCAL = 2
JENKINS = 3
CATEGORY_CHOICES = (
    (VARIABLES, 'Global Variables'),
    (LOCAL, 'Local Network Connection'),
    (JENKINS, 'Jenkins Connection'),
)


class Parameters(models.Model):
    VALUES_TYPES_CHOICES = (
        (1, 'String'),
        (2, 'List'),
    )
    name = models.CharField(_('name'), max_length=100)
    help_text = models.CharField(_('help text'), max_length=255, blank=True)
    category = models.IntegerField(_('category'), choices=CATEGORY_CHOICES, default=1)
    value_type = models.IntegerField(_('value type'), choices=VALUES_TYPES_CHOICES, default=1)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'parameters'
        verbose_name = _('parameter')
        verbose_name_plural = _('parameters')
        #ordering = ['name']

    def __str__(self):
        return '{0}'.format(self.name)


class TemplateServer(models.Model):
    name = models.CharField(_('name'), max_length=30)
    description = models.TextField(_('description'), blank=True)
    category = models.IntegerField(_('category'), choices=CATEGORY_CHOICES, default=1)
    parameters = models.ManyToManyField(Parameters, blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'servers_templates'
        verbose_name = _('server_template')
        verbose_name_plural = _('servers_templates')

    def __str__(self):
        return "{}".format(self.name)


class ServerProfile(models.Model):
    name = models.CharField(_('name'), unique=True, max_length=30)
    description = models.TextField(_('description'), blank=True)
    template = models.ForeignKey(TemplateServer, on_delete=models.DO_NOTHING)
    config = models.TextField(blank=True)
    category = models.IntegerField(_('category'), choices=CATEGORY_CHOICES, default=1)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'servers_profiles'
        verbose_name = _('server_profile')
        verbose_name_plural = _('server_profiles')

    def __str__(self):
        return '{0}'.format(self.name)

apps/Servers/views.py
import json
import paramiko
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from random import choice

from rolepermissions.checkers import has_role
from rolepermissions.mixins import HasPermissionsMixin
from scp import SCPClient
from string import ascii_lowercase, digits

from apps.Products.models import Source
from apps.Testings.models import Keyword, TestCase, TestSuite
from .forms import ServerProfileForm, ServerTemplateForm, ParametersForm
from .models import TemplateServer, ServerProfile, Parameters

from celery import shared_task


class ServerTemplateView(LoginRequiredMixin, HasPermissionsMixin, TemplateView):
    template_name = "servers-templates.html"
    required_permission = 'read_server_profile'


class NewServerTemplate(LoginRequiredMixin, HasPermissionsMixin, CreateView):
    template_name = "create-server-template.html"
    model = TemplateServer
    success_url = reverse_lazy('servers-templates')
    form_class = ServerTemplateForm
    required_permission = 'read_server_template'

    def get_context_data(self, **kwargs):
        context = super(NewServerTemplate, self).get_context_data(**kwargs)
        context['ParametersForm'] = ParametersForm
        context['stepper'] = self.kwargs.get('stepper')
        return context


class EditServerTemplate(LoginRequiredMixin, HasPermissionsMixin, UpdateView):
    model = TemplateServer
    template_name = "edit-server-template.html"
    success_url = reverse_lazy('servers-templates')
    form_class = ServerTemplateForm
    required_permission = "update_server_template"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user == request.user or request.user.is_staff:
            return super(EditServerTemplate, self).dispatch(request, *args, **kwargs)
        elif obj.user != request.user:
            messages.warning(request, "You don't have permission for this action")
            return redirect('servers-templates')

    def get_context_data(self, **kwargs):
        context = super(EditServerTemplate, self).get_context_data(**kwargs)
        context['ParametersForm'] = ParametersForm
        context['stepper'] = self.kwargs.get('stepper')
        return context


class DeleteServerTemplate(LoginRequiredMixin, HasPermissionsMixin, DeleteView):
    model = TemplateServer
    template_name = "delete-template.html"
    required_permission = "delete_server_template"

    def get_success_url(self):
        messages.success(self.request, "Template Deleted")
        return reverse_lazy('servers-templates')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user == request.user or request.user.is_staff:
            return super(DeleteServerTemplate, self).dispatch(request, *args, **kwargs)
        elif obj.user != request.user:
            messages.warning(request, "You don't have permission for this action")
            return redirect('servers-templates')


class ServerProfileView(LoginRequiredMixin, HasPermissionsMixin, TemplateView):
    template_name = "server-profiles.html"
    required_permission = 'read_server_profile'


class NewServerProfileView(LoginRequiredMixin, HasPermissionsMixin, CreateView):
    template_name = "create-server-profile.html"
    success_url = reverse_lazy('servers-profiles')
    form_class = ServerProfileForm
    required_permission = 'create_server_profile'

    def get_context_data(self, **kwargs):
        context = super(NewServerProfileView, self).get_context_data(**kwargs)
        context['stepper'] = self.kwargs.get('stepper')
        return context


class EditServerProfileView(LoginRequiredMixin, HasPermissionsMixin, UpdateView):
    template_name = "edit-server-profile.html"
    success_url = reverse_lazy('servers-profiles')
    form_class = ServerProfileForm
    model = ServerProfile
    required_permission = 'update_server_profile'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        can_edit = has_role(request.user, 'owner')
        if can_edit or obj.user == request.user:
            return super(EditServerProfileView, self).dispatch(request, *args, **kwargs)
        elif obj.user != request.user:
            messages.warning(request, "You don't have permission for this action")
            return redirect('servers-profiles')
    
    def get_context_data(self, **kwargs):
        context = super(EditServerProfileView, self).get_context_data(**kwargs)
        context['stepper'] = self.kwargs.get('stepper')
        return context


class DeleteServerProfile(LoginRequiredMixin, HasPermissionsMixin, DeleteView):
    model = ServerProfile
    template_name = "delete-profile.html"
    required_permission = 'delete_server_profile'

    def get_success_url(self):
        messages.success(self.request, "Profile Deleted")
        return reverse_lazy('servers-profiles')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        can_edit = has_role(request.user, 'owner')
        if can_edit or obj.user == request.user:
            return super(DeleteServerProfile, self).dispatch(request, *args, **kwargs)
        elif obj.user != request.user:
            messages.warning(request, "You don't have permission for this action")
            return redirect('servers-profiles')


class ParametersView(LoginRequiredMixin, HasPermissionsMixin, TemplateView):
    template_name = "parameters.html"
    required_permission = 'read_server_parameter'


class NewParametersView(LoginRequiredMixin, HasPermissionsMixin, CreateView):
    template_name = 'create-edit-parameter.html'
    success_url = reverse_lazy('parameters')
    form_class = ParametersForm
    required_permission = 'create_server_parameter'

    def form_valid(self, form):
        form.instance.user = self.request.user
        source = form.save()
        self.pk = source.pk
        return super(NewParametersView, self).form_valid(form)

    #def get_success_url(self):
    #    messages.success(self.request, "Parameter Created")
    #    return reverse_lazy('parameters')

    def get_success_url(self):
        stepper = self.kwargs.get('stepper')
        source_pk = self.pk
        if stepper != 'stepper':
            messages.success(self.request, "Parameter Created")
        if stepper != 'stepper':
            return reverse_lazy('parameters')
        else:
            return reverse_lazy('successful', kwargs={'step': 'parameters', 'pk': source_pk})

    def get_context_data(self, **kwargs):
        context = super(NewParametersView, self).get_context_data(**kwargs)
        context['title'] = 'Create Parameter'
        context['stepper'] = self.kwargs.get('stepper')
        return context


class EditParametersView(LoginRequiredMixin, HasPermissionsMixin, UpdateView):
    template_name = "create-edit-parameter.html"
    success_url = reverse_lazy("parameters")
    form_class = ParametersForm
    model = Parameters
    required_permission = 'update_server_parameter'

    def form_valid(self, form):
        form.instance.user = self.request.user
        source = form.save()
        self.pk = source.pk
        return super(EditParametersView, self).form_valid(form)

    def get_success_url(self):
        stepper = self.kwargs.get('stepper')
        source_pk = self.pk
        if stepper != 'stepper':
            messages.success(self.request, "Parameter Edited")
        if stepper != 'stepper':
            return reverse_lazy('parameters')
        else:
            return reverse_lazy('successful', kwargs={'step': 'parameters', 'pk': source_pk})

    def get_context_data(self, **kwargs):
        context = super(EditParametersView, self).get_context_data(**kwargs)
        context['title'] = 'Edit Parameter'
        context['stepper'] = self.kwargs.get('stepper')
        return context


class DeleteParametersView(LoginRequiredMixin, HasPermissionsMixin, DeleteView):
    model = Parameters
    template_name = "delete-parameters.html"
    required_permission = 'delete_server_parameter'

    # def dispatch(self, request, *args, **kwargs):
    #     obj = self.get_object()
    #     if obj.user == request.user or request.user.is_staff:
    #         return super(DeleteParametersView, self).dispatch(request, *args, **kwargs)
    #     elif obj.user != request.user:
    #         messages.warning(request, "You don't have permission for this action")
    #         return redirect('parameters')

    def get_success_url(self):
        messages.success(self.request, "Parameter Deleted")
        return reverse_lazy('parameters')


# - - - - - - - - - Run on Server functions - - - - - - - - - - -

def get_config_object(params):
    """get config object for connection"""
    data_result = dict()
    for var in params:
        try:
            param = Parameters.objects.get(pk=var.get('id'))
            data_result['{0}'.format(param.name)] = var.get('value')
        except Exception as error:
            data_result['text'] = '{0}'.format(error)
    return data_result


def get_connection(config):
    """Create a paramiko connection for ssh communication"""
    try:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        _port = 22
        if config.get('port'):
            _port = int(config.get('port'))
        client.connect(
            config.get('host'),
            username=config.get('user'),
            password=config.get('passwd'),
            port=_port)
    except Exception as error:
        client = error
    return client


def generate_filename(_script):
    """Generate a string like NAME_w0ln0t"""
    name = _script.replace(" ", "")
    random_string = ''.join(choice(ascii_lowercase + digits) for i in range(6))

apps/Servers/templates/create-edit-parameter.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block subtitle %}{{ title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="col s12">
                <p>
                        View to create parameters. These items are use to create templates and they can hold a value under profiles.
                        The parameters created here can only be used under the selected category group
                </p>
                <p>
                    <small>
                        <b>Category Groups:</b>
                        <ul style="">
                            <li>* Global Variables         ->   Variables that can be used under variables Profile</li>
                            <li>* Local Network connection -> Variables that can be used under Connection profile</li>
                            <li>* Jenkins connection       -> Variables that can be used under Jenkins profile</li>
                        </ul>
                    </small>
                </p>
        </div>
    </div>
    {% include "base-new-form.html" with url="/parameters/" %}
    {% if stepper != 'stepper' %}
    <div class="fixed-action-btn left-button ">
        <a href="{% url "parameters" %}" id="btn_play"
           class="btn-floating btn-large waves-effect waves-light grey">
            <i class="material-icons">arrow_back</i></a>
    </div>
    {% endif %}
{% endblock %}

apps/Servers/templates/create-server-profile.html
{% extends "base.html" %}
{% block title %}Create Server Profile{% endblock %}
{% block subtitle %}Create Server Profile{% endblock %}
{% block content %}
    <div class="container">
            <div class="col s12">
                    <p>
                        View to create profiles. Profiles are created based on templates. A template needs to be created first.
                        All parameters belonging to a template will be loaded on screen when selected. This can be populated with text can satisfy the intended purpose of the parameter
                    </p>
            </div>
        {% csrf_token %}
        <div class="row">
            <div class="col s12 l6 ">
                <div class="card">
                    <div class="card-content">
                        <form method="POST">
                            {% include "form-snippet.html" %}
                        </form>
                    </div>
                </div>
                <div class="card grey lighten-3 hide" id="instruction_box">
                    <div class="card-content">
                        <p><b class="red-text">*</b> <b class="blue-grey-text">Write the parameter value like python
                            syntax. </b></p>
                        <code>Example: "String", 1,
                            ["array", "string"], [1, 2, 3] or 1.2</code>

                    </div>
                </div>
            </div>
            <div class="col s12 l1">

            </div>
            <div class="col s12 l4 card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12 ">
                            <h4 class="card-title" id="category_template"></h4>
                            <h4 class="card-title">Parameters</h4>
                            <ul id="paramsList"></ul>
                            <code class="grey-text">* Only the parameters with value will be saved</code>
                        </div>
                    </div>
                    <div class="section">

                        <div class="center">
                            <button class="btn" type="button" disabled id="btn_create" onclick="saveProfile()">Create
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if stepper != 'stepper' %}
    <div class="fixed-action-btn left-button ">
        <a href="{% url "servers-profiles" %}" id="btn_play"
           class="btn-floating btn-large waves-effect waves-light grey tooltipped" data-position="right"
           data-tooltip="Back to Profile List">
            <i class="material-icons">arrow_back</i></a>
    </div>
    {% endif %}
{% endblock %}

{% block extraScripts %}
    <script type="text/javascript">
        var _select = document.getElementById('id_template');
        var _name = document.getElementById('id_name');
        var _desc = document.getElementById('id_description');
        var _categories = ['Global Variables', 'Local Network Connection', 'Jenkins Connection'];
        var _globalTemplate;

        _select.onchange = getParams;

        function getParams() {
            var box = document.getElementById('instruction_box');
            if (_select.value) {
                $.ajax({
                    url: "/apis/templates/" + _select.value,
                    type: "GET",
                    success: function (data) {
                        if (data.category === 1) {
                            box.classList.remove('hide');
                        } else {
                            box.classList.add('hide');
                        }
                        _globalTemplate = data;
                        var _category_type = document.getElementById('category_template');
                        _category_type.innerHTML = _categories[data.category - 1];
                        showParams(data.parameters)

                    }, error: function (err) {
                        console.log(err)
                    }
                })
            }
        }

        function showParams(params) {
            var _containerList = document.getElementById('paramsList');
            _containerList.innerHTML = '';
            params.forEach(function (v, k) {
                var _listElement = document.createElement('li');
                var _txtParam = document.createElement('span');
                _txtParam.innerHTML = v.name;
                _listElement.appendChild(_txtParam);
                if (v.help_text) {
                    var _help_icon = document.createElement('i');
                    _help_icon.setAttribute('class', 'material-icons tiny blue-grey-text');
                    _txtParam.setAttribute('data-tooltip', v.help_text);
                    _txtParam.setAttribute('class', 'tooltipped');
                    _help_icon.innerHTML = 'help';
                    _txtParam.appendChild(document.createTextNode(" "));
                    _txtParam.appendChild(_help_icon);
                }
                if (v.value_type === 2) {
                    var _chipContainer = document.createElement('div');
                    _chipContainer.setAttribute('id', v.id);
                    _chipContainer.setAttribute('class', 'chips param_val');
                    var _chipText = document.createTextNode('Put a value and press ENTER');
                    {#                    _chipText.setAttribute('class', 'blue-grey-text');#}
                    _listElement.appendChild(_chipText);
                    _listElement.appendChild(_chipContainer);
                } else {
                    var _input_value = document.createElement('input');
                    _input_value.setAttribute('type', 'Text');
                    _input_value.setAttribute('class', 'param_val');
                    _input_value.setAttribute('id', v.id);
                    _listElement.appendChild(_input_value);
                }

                _containerList.appendChild(_listElement)
            });
            document.getElementById('btn_create').disabled = false;
            $('.tooltipped').tooltip({delay: 20});
            $('.chips').material_chip();
        }

        function saveProfile() {
            /*First we obtain every value from inputs parameters*/
            var _values;
            var _params = [];
            var _cont;
            var _inputs = document.getElementsByClassName('param_val');
            var stepper = '{{stepper}}';

            for (_cont = 0; _cont < _inputs.length; _cont++) {
                var _current = _inputs[_cont];
                if (_current.classList.contains('chips')) {
                    var _chipData = $('#' + _current.id + '').material_chip('data');
                    _params.push({
                        'id': _current.id,
                        'value': _chipData
                    })
                } else {
                    _params.push({
                        'id': _current.id,
                        'value': _current.value
                    })
                }
            }
            _values = {
                "name": _name.value,
                "description": _desc.value,
                "template": _select.value,
                "category": _globalTemplate.category,
                "config": JSON.stringify(_params),
                "stepper": stepper
            };
            $.ajax({
                url: "{% url "api-profiles" %}",
                type: "POST",
                data: _values,
                success: function (data) {
                    var id = data.id;
                    if(stepper != 'stepper'){
                        window.location.replace("{% url "servers-profiles" %}");
                    } else {
                        window.location.href = generate_url(id);
                    }
                }, error: function (err) {
                    console.log(err)
                    if (err.responseJSON.name) {
                        (err.responseJSON.name).forEach(function (v) {
                            drawMessage("Name: " + v, 'red');
                        })
                    }
                }
            });
        }

        function generate_url(id) {
            return "{% url 'successful' step='profiles' pk=0 %}".replace("0", id);
        }
    </script>
{% endblock %}

apps/Servers/templates/delete-parameters.html
{% extends "base.html" %}
{% block title %}Delete Parameters {% endblock %}
{% block subtitle %}Delete Parameters {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="card-title">Are you sure you want to delete the follow Parameter?</p>
                        <ul>
                            <li><b>Name:</b> {{ object.name }}</li>
                            <li><b>Category:</b> {{ object.get_category_display }}</li>
                            <li><b>Value Type:</b> {{ object.get_value_type_display }}</li>
                            {% if object.help_text %}
                                <li><b>Help Text:</b> {{ object.help_text }}</li>
                            {% endif %}

                        </ul>
                        <div class="center">
                            <a href="{% url "parameters" %}" class="btn blue-grey">Back</a>
                            <input type="submit" value="Confirm" class="btn red"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/Servers/templates/delete-profile.html
{% extends "base.html" %}
{% block title %}Delete Profile {{ object.name }}{% endblock %}
{% block subtitle %}Delete Profile {{ object.name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="card-title">Are you sure you want to delete the follow Profile?</p>
                        <ul>
                            <li><b>Name:</b> {{ object.name }}</li>
                            <li><b>Description:</b> {{ object.description }}</li>
                        </ul>
                        <div class="center">
                            <a href="{% url "servers-profiles" %}" class="btn blue-grey">Back</a>
                            <input type="submit" value="Confirm" class="btn red"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/Servers/templates/delete-template.html
{% extends "base.html" %}
{% block title %}Delete Template {% endblock %}
{% block subtitle %}Delete Template {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-l3 l6 card">
                <div class="card-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="card-title">Are you sure you want to delete the follow Template?</p>
                        <ul>
                            <li><b>Name:</b> {{ object.name }}</li>
                            {% if object.description %}
                                <li><b>Description:</b> {{ object.description }}</li>
                            {% endif %}
                            {% if object.parameters.exists %}
                                <li><b>Parameters:</b>
                                    <ul>
                                        {% for param in object.parameters.all %}
                                            <li>{{ param.name }}</li>
                                        {% endfor %}

                                    </ul>
                                </li>
                            {% endif %}
                            {% if object.serverprofile_set.exists %}
                            <li><b>Profiles:</b>
                                <ul>
                                    {% for profile in object.serverprofile_set.all %}
                                    <li>{{ profile.name }}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endif %}
                        </ul>
                        <div class="center">
                            {% if object.serverprofile_set.exists %}
                            <div>
                                You can't delete this template because one or more profiles are linked to it
                            </div>
                            {% else %}
                                <input type="submit" value="Confirm" class="btn red"/>
                            {% endif %}
                            <a href="{% url "servers-templates" %}" class="btn blue-grey"> Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}